import type { Speaker } from "../types/speaker";

export const FEATURED_SPEAKERS: Speaker[] = [
  {
    name: "Don Ward",
    role: "Customer Engineer Specialist",
    company: "Google",
    imageUrl: "/speakers/don-ward.webp",
    imageAlt: "Don Ward",
    linkedinUrl: "https://www.linkedin.com/in/donwardpeng/",
    accentColor: "blue",
    bio: "Don Ward is a cloud enthusiast and Customer Engineer at Google Cloud, bringing deep practical experience to the table. In the last 5 years alone, he's earned an impressive 17 cloud certifications across Google and AWS, fueled by a passion for continuous learning and a drive to master the Google Cloud ecosystem. Don's commitment extends to the local tech scene, where he's spent 12 years fostering growth by leading Google Developer Groups in Windsor and Detroit. While transitioning leadership, he remains a dedicated volunteer, empowering others to lead.",
  },
  {
    name: "Keval Patel",
    role: "Lead Information Technology Infrastructure Manager",
    company: "Architecttura Inc., Architects",
    imageUrl: "/speakers/keval-patel.webp",
    imageAlt: "Keval Patel",
    linkedinUrl: "https://www.linkedin.com/in/kmpatel100/",
    accentColor: "green",
    bio: "Keval Patel is a Founder & AI Educator at Architecttura Inc., designing enterprise IT solutions and fostering the next generation of tech professionals.",
  },
  {
    name: "Elvis Akhalu",
    role: "Data Engineer",
    company: "TD",
    imageUrl: "/speakers/elvis-akhalu.webp",
    imageAlt: "Elvis Akhalu",
    linkedinUrl: "https://www.linkedin.com/in/elvisakhalu/",
    accentColor: "red",
    bio: "Elvis Akhalu is a Data Engineer at TD, building robust data pipelines and analytics infrastructure for financial services.",
  },
  {
    name: "Joe Youssouf",
    role: "Senior Data Scientist",
    company: "Oden Technologies",
    imageUrl: "/speakers/joe-youssouf.webp",
    imageAlt: "Joe Youssouf",
    linkedinUrl: "https://www.linkedin.com/in/joeyoussouf/",
    accentColor: "gold",
    bio: "Joe Youssouf is a Lead Customer Data Scientist at Oden Technologies, leveraging AI and machine learning to solve complex business challenges.",
  },
  {
    name: "Arunesh Choudhary",
    role: "Conversational AI Engineer",
    company: "Dialabot.ai",
    imageUrl: "/speakers/arunesh-choudhary.webp",
    imageAlt: "Arunesh Choudhary",
    linkedinUrl: "https://www.linkedin.com/in/aruneshchoudhary/",
    accentColor: "blue",
    bio: "As a Conversational AI Engineer at Dialabot.ai, I design, develop, and deploy scalable conversational AI agents tailored to business needs. I architect conversation flows, configure agent behaviors, and integrate agents with CRMs, APIs, calendars, and enterprise systems to automate workflows and improve user interactions. I also build and maintain data pipelines to support agent training, performance monitoring, and continuous optimization, ensuring reliable and production-ready AI solutions.",
  },
  {
    name: "Umair Durrani",
    role: "Data Scientist",
    company: "Presage Group",
    imageUrl: "/speakers/umair-durrani.webp",
    imageAlt: "Umair Durrani",
    linkedinUrl: "https://www.linkedin.com/in/durraniu/",
    accentColor: "green",
    bio: "Umair Durrani is a Data Scientist at Presage Group Inc., where he conducts scientific studies in the field of human factors and decision-making. Umair also develops web applications and data tools for optimizing data collection and reporting. With a PhD in Civil Engineering, he is passionate about modeling and mitigating human error in transportation systems. Umair also teaches data analysis workshops and frequently gives talks on topics such as R programming, Shiny apps, and open-source tools for transportation research.",
  },
  {
    name: "Troy Hector",
    role: "Client Data Analyst II | Supporting Google",
    company: "Mosaic North America",
    imageUrl: "/speakers/troy-hector.webp",
    imageAlt: "Troy Hector",
    linkedinUrl: "https://www.linkedin.com/in/itroyhector/",
    accentColor: "red",
    bio: "Troy Hector is a full-stack developer with more than 10 years of experience. After studying at St. Clair College, he now works as a Client Data Analyst II at Mosaic North America, supporting Google.",
  },
  {
    name: "Steven Rice",
    role: "Automation Specialist",
    company: "DataRealm",
    imageUrl: "/speakers/steven-rice.webp",
    imageAlt: "Steven Rice",
    linkedinUrl: "https://www.linkedin.com/in/stevenrice99/",
    accentColor: "gold",
    bio: "Steven Rice is an Automation Specialist at DataRealm.",
  },
  {
    name: "Florid Maclean",
    role: "CEO & Professor",
    company: "Catch The Event | Fanshawe College",
    imageUrl: "/speakers/florid-maclean.webp",
    imageAlt: "Florid Maclean",
    linkedinUrl: "https://www.linkedin.com/in/florid-maclean/",
    accentColor: "blue",
    bio: "Florid Maclean is CEO of Catch The Event and a professor at Fanshawe College.",
  },
  {
    name: "Sandra Lopez-Zamora",
    role: "Senior Manager - Data Strategy and Analytics",
    company: "Scotiabank",
    imageUrl: "/speakers/sandra-lopez-zamora.webp",
    imageAlt: "Sandra Lopez-Zamora",
    linkedinUrl: "https://www.linkedin.com/in/slopezza/",
    accentColor: "green",
    bio: "Sandra Lopez-Zamora is a Senior Manager in Data Strategy and Analytics at Scotiabank.",
  },
  {
    name: "Diaa ElKott",
    role: "Senior Software Engineer",
    company: "ISRA VISION - Part of Atlas Copco",
    imageUrl: "/speakers/diaa-elkott.webp",
    imageAlt: "Diaa ElKott",
    linkedinUrl: "https://www.linkedin.com/in/elkott/",
    accentColor: "red",
    bio: "Diaa ElKott is a Senior Software Engineer at ISRA VISION, part of Atlas Copco.",
  },
  {
    name: "Kylie Kiser",
    role: "Owner",
    company: "Kylie K Consulting",
    imageUrl: "/speakers/kylie-kiser.webp",
    imageAlt: "Kylie Kiser",
    linkedinUrl: "https://www.linkedin.com/in/kylie-kiser/",
    accentColor: "gold",
    bio: "Kylie Kiser is the owner of Kylie K Consulting.",
  },
  {
    name: "Andrea Irina Yzeiri",
    role: "Chief Data & Analytics Officer and Lead AI Engineer",
    company: "Picsume",
    imageUrl: "/speakers/andrea-irina-yzeiri.webp",
    imageAlt: "Andrea Irina Yzeiri",
    linkedinUrl: "https://www.linkedin.com/in/andrea-yzeiri/",
    accentColor: "blue",
    bio: "Andrea Irina Yzeiri is Chief Data & Analytics Officer and Lead AI Engineer at Picsume.",
  },
  {
    name: "Mina Girges",
    role: "Vice President & Chief Information Officer",
    company: "TransForm Shared Service Organization",
    imageUrl: "/speakers/mina-girges.webp",
    imageAlt: "Mina Girges",
    linkedinUrl: "https://www.linkedin.com/in/minagirges/",
    accentColor: "green",
    bio: "Mina Girges is Vice President and Chief Information Officer at TransForm Shared Service Organization.",
  },
  {
    name: "Amrit Mehta",
    role: "Senior Advisor",
    company: "Deloitte",
    imageUrl: "/speakers/amrit-mehta.webp",
    imageAlt: "Amrit Mehta",
    linkedinUrl: "https://www.linkedin.com/in/amritmehta/",
    accentColor: "red",
    bio: "Amrit Mehta is a Senior Advisor at Deloitte.",
  },
  {
    name: "Frank Abbruzzese",
    role: "CEO & President",
    company: "AlphaKOR",
    imageUrl: "/speakers/frank-abbruzzese.webp",
    imageAlt: "Frank Abbruzzese",
    linkedinUrl: "https://www.linkedin.com/in/frankabbruzzese/",
    accentColor: "gold",
    bio: "Frank Abbruzzese is CEO and President of AlphaKOR.",
  },
  {
    name: "Veronica Reingold",
    role: "Computer Science Student",
    company: "University of Windsor",
    imageUrl: "/speakers/veronica-reingold.webp",
    imageAlt: "Veronica Reingold",
    linkedinUrl: "https://www.linkedin.com/in/veronicareingold/",
    accentColor: "blue",
    bio: "Veronica Reingold is a Computer Science student at the University of Windsor.",
  },
  {
    name: "Wen Teoh",
    role: "President & Principal Consultant",
    company: "",
    imageUrl: "/speakers/wen-teoh.webp",
    imageAlt: "Wen Teoh",
    linkedinUrl: "https://www.linkedin.com/in/wen-teoh/",
    accentColor: "green",
    bio: "Wen Teoh is a President and Principal Consultant.",
  },
  {
    name: "Sean Bridgeman",
    role: "Director of Product Management",
    company: "HALIGHT Inc",
    imageUrl: "/speakers/sean-bridgeman.webp",
    imageAlt: "Sean Bridgeman",
    linkedinUrl: "https://www.linkedin.com/in/sean-bridgeman-b2a30a178/",
    accentColor: "red",
    bio: "Sean Bridgeman is Director of Product Management at HALIGHT Inc.",
  },
  {
    name: "Camila Gaitan",
    role: "Systems Engineer | Business Data Analyst",
    company: "Softgic",
    imageUrl: "/speakers/camila-gaitan.webp",
    imageAlt: "Camila Gaitan",
    linkedinUrl: "https://www.linkedin.com/in/lizeth-camila-gaitan-baron/",
    accentColor: "gold",
    bio: "Camila Gaitan is a Systems Engineer and Business Data Analyst at Softgic.",
  },
  {
    name: "Kevin Serrano Mojica",
    role: "Software Engineer | Android Developer",
    company: "Mercado Libre",
    imageUrl: "/speakers/kevin-serrano-mojica.webp",
    imageAlt: "Kevin Serrano Mojica",
    linkedinUrl: "https://www.linkedin.com/in/kevinserranomojica/",
    accentColor: "blue",
    bio: "Kevin Serrano Mojica is a Software Engineer and Android Developer at Mercado Libre.",
  },
  {
    name: "Vimal K.",
    role: "Co-Founder",
    company: "GDG Cloud Toronto",
    imageUrl: "/speakers/vimal-k.webp",
    imageAlt: "Vimal K.",
    linkedinUrl: "https://www.linkedin.com/in/vimalonline/",
    accentColor: "green",
    bio: "Vimal K. is a Co-Founder of GDG Cloud Toronto.",
  },
  {
    name: "Atif Khan",
    role: "Chief Technology Officer",
    company: "DataBraid",
    imageUrl: "/speakers/atif-khan.webp",
    imageAlt: "Atif Khan",
    linkedinUrl: "https://www.linkedin.com/in/atifikhan/",
    accentColor: "red",
    bio: "Atif Khan is Chief Technology Officer at DataBraid.",
  },
  {
    name: "Yvonne Pilon",
    role: "President & CEO",
    company: "WEtech Alliance",
    imageUrl: "/speakers/yvonne-pilon.webp",
    imageAlt: "Yvonne Pilon",
    linkedinUrl: "https://www.linkedin.com/in/yvonnepilon/",
    accentColor: "gold",
    bio: "Yvonne Pilon is President and CEO of WEtech Alliance.",
  },
  {
    name: "James Lannigan",
    role: "Senior Research Associate (Innovation and Technology)",
    company: "Signal49 Research",
    imageUrl: "/speakers/james-lannigan.webp",
    imageAlt: "James Lannigan",
    linkedinUrl: "https://www.linkedin.com/in/james-lannigan-phd/",
    accentColor: "blue",
    bio: "James Lannigan is a Senior Research Associate in Innovation and Technology at Signal49 Research.",
  },
  {
    name: "Aasha Khan",
    role: "Founder & Lead Organizer",
    company: "Youth Tech Labs",
    imageUrl: "/speakers/aasha-khan.webp",
    imageAlt: "Aasha Khan",
    linkedinUrl: "https://www.linkedin.com/in/aasha-khan-3a2294250/",
    accentColor: "green",
    bio: "Aasha Khan is Founder and Lead Organizer of Youth Tech Labs.",
  },
];