import type { Speaker } from "../types/speaker";

export const FEATURED_SPEAKERS: Speaker[] = [
  // KEYNOTE SPEAKERS (Featured - First 4)
  {
    name: "Don Ward",
    role: "Customer Engineer Specialist",
    company: "Google",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Don Ward",
    linkedinUrl: "https://www.linkedin.com/in/donwardpeng/",
    accentColor: "blue",
    bio: "Don Ward is a cloud enthusiast and Customer Engineer at Google Cloud, bringing deep practical experience to the table. In the last 5 years alone, he's earned an impressive 17 cloud certifications across Google and AWS, fueled by a passion for continuous learning and a drive to master the Google Cloud ecosystem. Don's commitment extends to the local tech scene, where he's spent 12 years fostering growth by leading Google Developer Groups in Windsor and Detroit. While transitioning leadership, he remains a dedicated volunteer, empowering others to lead.",
  },
  {
    name: "Keval Patel",
    role: "Founder & AI Educator",
    company: "Architecttura Inc., Architects",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Keval Patel",
    linkedinUrl: "https://www.linkedin.com/in/kmpatel100/",
    accentColor: "yellow",
    bio: "Keval Patel is a Founder & AI Educator at Architecttura Inc., designing enterprise IT solutions and fostering the next generation of tech professionals.",
  },
  {
    name: "Elvis Akhalu",
    role: "Data Engineer",
    company: "TD",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Elvis Akhalu",
    linkedinUrl: "https://www.linkedin.com/in/elvisakhalu/",
    accentColor: "red",
    bio: "Elvis Akhalu is a Data Engineer at TD, building robust data pipelines and analytics infrastructure for financial services.",
  },
  {
    name: "Joe Youssouf",
    role: "Lead Customer Data Scientist",
    company: "Oden Technologies",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Joe Youssouf",
    linkedinUrl: "https://www.linkedin.com/in/joeyoussouf/",
    accentColor: "green",
    bio: "Joe Youssouf is a Lead Customer Data Scientist at Oden Technologies, leveraging AI and machine learning to solve complex business challenges.",
  },
  {
    name: "Arunesh Choudhary",
    role: "Conversational AI Engineer",
    company: "Dialabot.ai",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Arunesh Choudhary",
    linkedinUrl: "https://www.linkedin.com/in/aruneshchoudhary/",
    accentColor: "blue",
    bio: "As a Conversational AI Engineer at Dialabot.ai, I design, develop, and deploy scalable conversational AI agents tailored to business needs. I architect conversation flows, configure agent behaviors, and integrate agents with CRMs, APIs, calendars, and enterprise systems to automate workflows and improve user interactions. I also build and maintain data pipelines to support agent training, performance monitoring, and continuous optimization, ensuring reliable and production-ready AI solutions.",
  },
  {
    name: "Umair Durrani",
    role: "Data Scientist",
    company: "Presage Group",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Umair Durrani",
    linkedinUrl: "https://www.linkedin.com/in/durraniu/",
    accentColor: "green",
    bio: "Umair Durrani is a Data Scientist at Presage Group Inc., where he conducts scientific studies in the field of human factors and decision-making. Umair also develops web applications and data tools for optimizing data collection and reporting. With a PhD in Civil Engineering, he is passionate about modeling and mitigating human error in transportation systems. Umair also teaches data analysis workshops and frequently gives talks on topics such as R programming, Shiny apps, and open-source tools for transportation research.",
  },
  {
    name: "Troy Hector",
    role: "Client Data Analyst II",
    company: "Mosaic North America",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Troy Hector",
    linkedinUrl: "https://www.linkedin.com/in/itroyhector/",
    accentColor: "red",
    bio: "Troy Hector is a full-stack developer with more than 10 years of experience. After studying at St. Clair College, he now works as a Client Data Analyst II at Mosaic North America, supporting Google.",
  },

  // ORGANIZERS & FACILITATORS (Show after "View all speakers")
  {
    name: "Ali El-Sharif",
    role: "Professor",
    company: "St. Clair College",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Ali El-Sharif",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "blue",
    bio: "Ali El-Sharif is a Professor at St. Clair College and one of the key organizers of GDG Windsor DevFest 2026.",
  },
  {
    name: "Vivian Tang",
    role: "Data Consultant",
    company: "BDO",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Vivian Tang",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "yellow",
    bio: "Vivian Tang is a Data Consultant at BDO with expertise in data analytics and business intelligence.",
  },
  {
    name: "Daria Deriagina",
    role: "Developer",
    company: "DashDev",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Daria Deriagina",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "red",
    bio: "Daria is a talented developer at DashDev and an organizer of GDG Windsor.",
  },
  {
    name: "Ron Mckenzie",
    role: "Teacher",
    company: "Greater Essex County District School Board",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Ron Mckenzie",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "green",
    bio: "Ron Mckenzie is an educator and facilitator dedicated to inspiring the next generation of tech professionals.",
  },
  {
    name: "Rob Chaykoski",
    role: "Lead Security Engineer",
    company: "Ontario Health",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Rob Chaykoski",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "blue",
    bio: "Rob Chaykoski is a Lead Security Engineer at Ontario Health, specializing in healthcare cybersecurity.",
  },
  {
    name: "Esraa Abdelhalim",
    role: "Assistant Professor",
    company: "University of Windsor",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Esraa Abdelhalim",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "yellow",
    bio: "Esraa Abdelhalim is an Assistant Professor at the University of Windsor, conducting research in computer science.",
  },
  {
    name: "Ashlynn Ward",
    role: "Computer Science Student",
    company: "University of Windsor",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Ashlynn Ward",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "red",
    bio: "Ashlynn Ward is a passionate Computer Science student at the University of Windsor.",
  },
  {
    name: "ranem ghalion",
    role: "AI Engineer",
    company: "Hackforge",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "ranem ghalion",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "green",
    bio: "ranem ghalion is an AI Engineer at Hackforge, working on innovative AI solutions.",
  },
  {
    name: "Sam Ghasan",
    role: "Enterprise Architect",
    company: "Tech Solutions",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Sam Ghasan",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "blue",
    bio: "Sam Ghasan is an Enterprise Architect designing scalable solutions for complex organizational challenges.",
  },
  {
    name: "Kiran Puthan",
    role: "Solution Consultant",
    company: "Ordway Labs",
    imageUrl: "/speaker-placeholder.png",
    imageAlt: "Kiran Puthan",
    linkedinUrl: "https://www.linkedin.com/",
    accentColor: "red",
    bio: "Kiran Puthan is a Solution Consultant at Ordway Labs, helping organizations implement effective technology solutions.",
  },
];
